#!/bin/sh

wp core download --path=wp-plugin
cd wp-plugin
wp config create --dbname=wp_wcj_cal_dev --dbuser=root --dbpass=
wp db create
wp core install --url=wp-wcjcal.dev --title="Local Dev WP - WCJ Calendar" --admin_user=admin --admin_password=admin --admin_email=admin@wcjcal.dev
cd ..